peterson:
	gcc peterson.c -o peterson -lpthread

atomic:
	gcc atomic.c -o atomic -lpthread

mutex:
	gcc mutex.c -o mutex -lpthread

semaphore:
	gcc semaphore.c -o semaphore -lpthread

filosofo:
	gcc filosofos.c -o filosofo -lpthread

deadlock:
	gcc deadlock.c -o deadlock -lpthread
