name: 🧐 Fiscal de Padrão

on:
  push:
    branches: [ main ]

jobs:
  check-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Baixando o código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Verificando nomes dos arquivos
        run: |
          FILES=$(git diff --name-only --diff-filter=A origin/main...HEAD)
          REGEX="^([0-9]{4}|20XX)_[1-2X](\([0-9]+\))?(_[a-zA-Z0-9]+)?\.(pdf|jpg|png|jpeg)$"
          ERROS=0
          
          IFS=$'\n'
          for FILE in $FILES; do
            if [[ -n "$FILE" && "$FILE" != "docs/"* && "$FILE" != "scripts/"* && "$FILE" != .* ]]; then
              FILENAME=$(basename "$FILE")
              if [[ ! $FILENAME =~ $REGEX ]]; then
                echo "❌ ERRO: O arquivo '$FILENAME' não segue o padrão <ano>_<semestre>. (Caminho: $FILE)"
                ERROS=1
              fi
            fi
          done
          unset IFS
          
          if [ $ERROS -eq 1 ]; then
            echo "Por favor, renomeie os arquivos seguindo o CONTRIBUTING.md."
            exit 1
          else
            echo "✅ Todos os arquivos estão no padrão correto!"
          fi
